Blog/urls.py
from django.urls import path
from .views import (
    HomeListView,
    Article_function,
    BlogsCreateView,
    OneUserPostsListView,
    UserPostsListView,
    BlogsUpdateView,
    BlogsDeleteView,
    SearchResultsView,
)


app_name = 'Blog'


urlpatterns = [
    path('', HomeListView.as_view(), name='Home'),
    path('add', BlogsCreateView.as_view(), name='Add'),
    path('update/<pk>/', BlogsUpdateView.as_view(), name='Update'),
    path('delete/<pk>/', BlogsDeleteView.as_view(), name='Delete'),
    path('userposts', OneUserPostsListView.as_view(), name='UserPosts'),
    path('results/', SearchResultsView.as_view(), name='Search'),
    path('posts=<username>', UserPostsListView.as_view(), name='Posts'),
    path('post/<id>/', Article_function, name='Article'),
]

BlogSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Blog.urls')),
    path('users/', include('Users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import path
from .views import (
    Home,
    SignUp_function,
    SignIn_function,
    SignOut_function,
    Settings_function,
)

app_name = 'Users'

urlpatterns = [
    path('', Home, name='Home'),
    path('signup', SignUp_function, name='SignUp'),
    path('signin', SignIn_function, name='SignIn'),
    path('signout', SignOut_function, name='SignOut'),
    path('settings', Settings_function, name='Settings'),
]

Blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.


class PostsModel(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    body = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse("Blog:Article", kwargs={'id': self.id})

Blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import PostsModel
from django.contrib.auth.models import User
from django.contrib.auth.mixins import UserPassesTestMixin
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.db.models import Q

# Create your views here.


class HomeListView(ListView):
    model = PostsModel
    template_name = 'main/Home.html'
    ordering = '-pub_date'
    paginate_by = 3


class SearchResultsView(ListView):
    model = PostsModel
    template_name = 'main/search.html'
    ordering = '-pub_date'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = PostsModel.objects.filter(Q(title__icontains=query))
        return object_list


class UserPostsListView(ListView):
    model = PostsModel
    template_name = 'main/userPosts.html'
    ordering = '-pub_date'
    paginate_by = 2

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return PostsModel.objects.filter(author=user).order_by('-pub_date')


def Article_function(request, id):
    posts = PostsModel.objects.get(id=id)
    context = {
        'posts': posts,
        'id': id,
    }
    return render(request, 'main/Article.html', context)


class BlogsCreateView(CreateView):
    model = PostsModel
    template_name = 'main/Add_Post.html'
    fields = ['title', 'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class BlogsUpdateView(UpdateView, UserPassesTestMixin):
    model = PostsModel
    template_name = 'main/Update.html'
    fields = ['title', 'body']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_function(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class BlogsDeleteView(DeleteView, UserPassesTestMixin):
    model = PostsModel
    template_name = 'main/Delete.html'
    success_url = '/'

    def test_function(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


class OneUserPostsListView(ListView):
    posts = PostsModel
    template_name = 'main/onlyOneUserPosts.html'
    ordering = '-pub_date'
    paginate_by = 2

    def get_queryset(self):
        return PostsModel.objects.filter(author=self.request.user).reverse()

Blog/templates/main/Add_Post.html
{% extends 'main/Index.html' %}
{% load bootstrap5 %}
{% block title %}
Add Post
{% endblock title %}

{% block content %}
<div class="row my-3">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="box-element p-3">
      <form class="" action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="d-grid gap-2">
          {% bootstrap_button 'Add Post' button_type='submit' button_class='btn-outline-primary' size='sm' %}
        </div>
      </form>
    </div>
  </div>
  <div class="col-md-3"></div>
</div>

{% endblock content %}

Blog/templates/main/Article.html
{% extends 'main/Index.html' %}
{% load static %}
{% load bootstrap5 %}

{% block title %}
    Home
{% endblock title %}


{% block content %}

  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-7">

      <div class="box-element my-3">
        <div class="card border-info">
          <div class="card-header ">
            <img src="{{ posts.author.userprofile.image.url }}" width="30" height="30" class="rounded-circle me-2" alt="Img">
            <span class="fs-5 me-5"><a href="{% url 'Blog:Posts' posts.author.username %}" class="text-dark">{{ posts.author }}</a></span>
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ posts.title }}</h5>
            <p class="card-text">{{ posts.body }}</p>
          </div>
        </div>
      </div><!-- box-element end -->

    </div><!-- Col-md-7 end -->
    <div class="col-md-4">
      <div class="box-element p-3 mt-4">
        <table class="table border-primary">
          <tr>
            <td><i class="fas fa-user-edit"></i> Author</td>
            <td><a href="{% url 'Blog:Posts' posts.author.username %}" class="text-dark">{{ posts.author | upper }}</a></td>
          </tr>
          <tr>
            <td><i class="fas fa-blog"></i> Title</td>
            <td>{{ posts.title | upper }}</td>
          </tr>
          <tr>
            <td><i class="fas fa-calendar-alt"></i> Published_Date</td>
            <td>{{ posts.pub_date }}</td>
          </tr>
        </table>
      </div>
    </div>
  </div><!-- row end -->
{% endblock content %}

Blog/templates/main/Delete.html
{% extends 'main/Index.html' %}
{% load bootstrap5 %}
{% block title %}
  Delete
{% endblock title %}

{% block content %}

<div class="main">
  <div class="container">
    <form action="" method="post">
      {% csrf_token %}
      <h1>Welcome Delete Section</h1>
      <h3>Are You sure Delete <b class="fs-2">"{{ object.title }}"</b></h3>
      <small><mark class="bg-warning">WARNING!</mark> You can't return this Item</small><br><br>
      <button type="submit" name="button" class="btn btn-danger">Yes I'm sure</button>
      <a href="{% url 'Blog:UserPosts' %}" class="ms-3">Cancel</a>
    </form>
  </div>
</div>

{% endblock content %}

Blog/templates/main/Home.html
{% extends 'main/Index.html' %}
{% load static %}
{% load bootstrap5 %}

{% block title %}
    Home
{% endblock title %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
{% for post in object_list %}
      <div class="box-element my-3">
        <div class="card border-info">
          <div class="card-header ">
            <img src="{{ post.author.userprofile.image.url }}" width="30" height="30" class="rounded-circle me-2" alt="Img">
            <span class="fs-5 me-5"><a href="{% url 'Blog:Posts' post.author.username %}" class="text-dark">{{ post.author }}</a></span>
            <!-- <small class="text-end fs-7 ms-5">{{ post.pub_date }}</small> -->
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">{{ post.body | truncatechars:150 }}</p>
            <a href="{% url 'Blog:Article' id=post.id %}" class="btn btn-primary">Read Full</a>
          </div>
        </div>
      </div><!-- box-element end -->
{% endfor %}
    </div><!-- Col-md-7 end -->
    <div class="col-md-2"></div>
  </div><!-- row end -->
</div>
{% endblock content %}

Blog/templates/main/Index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- fontawesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
{% include 'main/messeges.html' %}
  <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light px-5">
    <div class="container">
      <a class="navbar-brand" href="{% url 'Blog:Home' %}"><b>Django</b>Blog</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'Blog:Home' %}"><i class="fas fa-home"></i>Home</a>
          </li>
        </ul>
        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3 me-2" action="{% url 'Blog:Search' %}" method="get">
          <input type="search" name="q" class="form-control form-control-dark" placeholder="Search..." aria-label="Search" value="">
        </form>
        {% if user.is_authenticated %}
          <a href="{% url 'Users:Home' %}"><i class="fas fa-user-circle fs-4 text-dark"></i></a>
        {% else %}
          <div class="text-end">
            <a href="{% url 'Users:SignIn' %}" class="btn btn-outline-success me-2"><i class="fas fa-sign-in-alt"></i>
                SignIn</a>
            <a href="{% url 'Users:SignUp' %}" class="btn btn-warning">SignUp</a>
          </div>
        {% endif %}
      </div>
    </div>
  </nav>

  <div class="main mx-5">
      {% block content %}


      {% endblock content %}
  </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>

Blog/templates/main/Update.html
{% extends 'main/Index.html' %}
{% load bootstrap5 %}
{% block title %}
  Update
{% endblock title %}

{% block content %}
<div class="row my-3">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="box-element p-3">
      <form class="" action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="d-grid gap-2">
          {% bootstrap_button 'Update' button_type='submit' button_class='btn-outline-primary' size='sm' %}
        </div>
      </form>
    </div>
  </div>
  <div class="col-md-3"></div>
</div>

{% endblock content %}

Blog/templates/main/messeges.html
<!doctype html>
{% load static %}
{% load bootstrap5 %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title></title>
  </head>
  <body>
  <div class="alert-class" style="margin-top: 60px;">
    {% if messages %}
      {% for message in messages %}
      <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
    {% endif %}

    <!-- {% bootstrap_alert 'Test' alert_type='success' %} -->
  </div>


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

Blog/templates/main/onlyOneUserPosts.html
{% extends 'main/Index.html' %}
{% load static %}
{% load bootstrap5 %}

{% block title %}
    Home
{% endblock title %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
{% for post in object_list %}
      <div class="box-element my-3">
        <div class="card border-info">
          <div class="card-header ">
            <img src="{{ post.author.userprofile.image.url }}" width="30" height="30" class="rounded-circle me-2" alt="Img">
            <span class="fs-5 me-5"><a href="#" class="text-dark">{{ post.author }}</a></span>
            <!-- <small class="text-end fs-7 ms-5">{{ post.pub_date }}</small> -->
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">{{ post.body | truncatechars:150 }}</p>
            <a href="{% url 'Blog:Article' id=post.id %}" class="btn btn-primary">Read Full</a>
            <span><a href="{% url 'Blog:Update' pk=post.pk %}" class="btn btn-outline-warning ms-2">Edit</a></span>
            <span><a href="{% url 'Blog:Delete' pk=post.pk %}" class="btn btn-danger ms-2">Delete</a></span>
          </div>
        </div>
      </div><!-- box-element end -->
{% endfor %}
{% if is_paginated %}
    <nav aria-label="Page navigation example" id="pagination">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page=1">First</a>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
        {% endif %}
      </ul>
    </nav>
{% endif %}
    </div><!-- Col-md-7 end -->
    <div class="col-md-2"></div>
  </div><!-- row end -->
</div>
{% endblock content %}

Blog/templates/main/search.html
{% extends 'main/Index.html' %}
{% load static %}
{% load bootstrap5 %}

{% block title %}
    Search
{% endblock title %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
{% for post in object_list %}
      <div class="box-element my-3">
        <div class="card border-info">
          <div class="card-header ">
            <img src="{{ post.author.userprofile.image.url }}" width="30" height="30" class="rounded-circle me-2" alt="Img">
            <span class="fs-5 me-5"><a href="{% url 'Blog:Posts' post.author.username %}" class="text-dark">{{ post.author }}</a></span>
            <!-- <small class="text-end fs-7 ms-5">{{ post.pub_date }}</small> -->
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">{{ post.body | truncatechars:150 }}</p>
            <a href="{% url 'Blog:Article' id=post.id %}" class="btn btn-primary">Read Full</a>
          </div>
        </div>
      </div><!-- box-element end -->
{% endfor %}
{% if is_paginated %}
    <nav aria-label="Page navigation example" id="pagination">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page=1">First</a>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
        {% endif %}
      </ul>
    </nav>
{% endif %}
    </div><!-- Col-md-7 end -->
    <div class="col-md-2"></div>
  </div><!-- row end -->
</div>
{% endblock content %}

Blog/templates/main/userPosts.html
{% extends 'main/Index.html' %}
{% load static %}
{% load bootstrap5 %}

{% block title %}
    Home
{% endblock title %}


{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
{% for post in object_list %}
      <div class="box-element my-3">
        <div class="card border-info">
          <div class="card-header ">
            <img src="{{ post.author.userprofile.image.url }}" width="30" height="30" class="rounded-circle me-2" alt="Img">
            <span class="fs-5 me-5"><a href="{% url 'Blog:Posts' post.author.username %}" class="text-dark">{{ post.author }}</a></span>
            <!-- <small class="text-end fs-7 ms-5">{{ post.pub_date }}</small> -->
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">{{ post.body | truncatechars:150 }}</p>
            <a href="{% url 'Blog:Article' id=post.id %}" class="btn btn-primary">Read Full</a>
          </div>
        </div>
      </div><!-- box-element end -->
{% endfor %}
{% if is_paginated %}
    <nav aria-label="Page navigation example" id="pagination">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1" aria-disabled="true">Previous</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page=1">First</a>
            </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
            </li>
            <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
            </li>
        {% endif %}
      </ul>
    </nav>
{% endif %}
    </div><!-- Col-md-7 end -->
    <div class="col-md-2"></div>
  </div><!-- row end -->
</div>
{% endblock content %}