Blog/urls.py
from django.urls import path
from .views import (
    HomeListView,
    Article_function,
    BlogsCreateView,
    OneUserPostsListView,
    UserPostsListView,
    BlogsUpdateView,
    BlogsDeleteView,
    SearchResultsView,
)


app_name = 'Blog'


urlpatterns = [
    path('', HomeListView.as_view(), name='Home'),
    path('add', BlogsCreateView.as_view(), name='Add'),
    path('update/<pk>/', BlogsUpdateView.as_view(), name='Update'),
    path('delete/<pk>/', BlogsDeleteView.as_view(), name='Delete'),
    path('userposts', OneUserPostsListView.as_view(), name='UserPosts'),
    path('results/', SearchResultsView.as_view(), name='Search'),
    path('posts=<username>', UserPostsListView.as_view(), name='Posts'),
    path('post/<id>/', Article_function, name='Article'),
]

BlogSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Blog.urls')),
    path('users/', include('Users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Users/urls.py
from django.urls import path
from .views import (
    Home,
    SignUp_function,
    SignIn_function,
    SignOut_function,
    Settings_function,
)

app_name = 'Users'

urlpatterns = [
    path('', Home, name='Home'),
    path('signup', SignUp_function, name='SignUp'),
    path('signin', SignIn_function, name='SignIn'),
    path('signout', SignOut_function, name='SignOut'),
    path('settings', Settings_function, name='Settings'),
]

Users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
"""Create your models here."""


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile_pic', default='user.png')

    def __str__(self):
        return f'{self.user} PROFILE'

    def save(self, *args, **kwargs):
        return super().save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.width > 300 and img.height > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

Users/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def save(self, commit=True):
        user = super(UserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class UpdateUser(forms.ModelForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email']

    def save(self, commit=True):
        user = super(UpdateUser, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user


class UpdateProfile(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image']

Users/views.py
from .forms import UserForm, UpdateUser, UpdateProfile
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from .models import UserProfile

# Create your views here.


def Home(request):
    if request.user.is_authenticated:
        user = request.user
        user, created = UserProfile.objects.get_or_create(user=user)

    return render(request, 'index/UserHome.html')


def SignUp_function(request):
    if request.user.is_authenticated:
        user = request.user
        user, created = UserProfile.objects.get_or_create(user=user)
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Welcome New User')
            return redirect('Users:Home')
    form = UserForm
    return render(request, 'register/signUp.html', context={'form': form})


def SignIn_function(request):
    if request.user.is_authenticated:
        user = request.user
        user, created = UserProfile.objects.get_or_create(user=user)
    if request.method == 'POST':
        forms = AuthenticationForm(data=request.POST)
        if forms.is_valid():
            username = forms.cleaned_data.get('username')
            password = forms.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f'Good Job {user.username}')
                return redirect('Users:Home')
            else:
                messages.error(request, 'Something went to wrong!')
        else:
            messages.error(request, 'Something went to wrong!')
    forms = AuthenticationForm
    return render(request, 'register/signIn.html', context={'login_form': forms})


def SignOut_function(request):
    logout(request)
    messages.info(request, 'Good Bie :( ')
    return redirect('Blog:Home')


def Settings_function(request):
    if request.method == 'POST':
        form_u = UpdateUser(data=request.POST, instance=request.user)
        form_p = UpdateProfile(request.POST, request.FILES,
                               instance=request.user.userprofile)
        if form_u.is_valid() and form_p.is_valid():
            form_u.save()
            form_p.save()
            messages.success(request, 'User UPDATED')
            return redirect('Users:Home')
    else:
        form_u = UpdateUser(instance=(request.user))
        form_p = UpdateProfile(instance=(request.user.userprofile))
    context = {
        'form_u': form_u,
        'form_p': form_p,
    }
    return render(request, 'register/Settings.html', context)

Users/templates/index/UserHome.html
{% extends 'index/index.html' %}
{% load bootstrap5 %}
{% block title %}
    PROFILE
{% endblock title %}

{% block content %}
<div class="row" style="margin-top: 70px;">
  <div class="col-md-3"></div>
  <div class="col-md-6">
    <div class="box-element p-3">
        <div class="card mb-3" >
          <div class="row g-0">
            <div class="col-md-4">
                <a href="{{ user.userprofile.image.url }}">
                    <img src="{{ user.userprofile.image.url }}" alt="UserImg" class="img-fluid rounded-circle p-3">
                </a>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <table class="table mt-4 table-hover">
                    <tr>
                        <td><i class="fas fa-user-tie"></i> USERNAME</td>
                        <td>{{ user.username | upper }}</td>
                    </tr>
                    <tr>
                        <td><i class="fas fa-at"></i> EMAIL</td>
                        <td>{{ user.email }}</td>
                    </tr>
                    <tr>
                        <td colspan="2"><a href="{% url 'Users:Settings' %}" class="btn btn-primary btn-sm px-4"><i class="fas fa-sliders-h"></i> Settings</a></td>
                    </tr>
                </table>
              </div>
            </div>
          </div>
        </div>
    </div>
  </div>
  <div class="col-md-3"></div>
</div>

{% endblock content %}

Users/templates/index/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- fontawesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
{% include 'index/messeges.html' %}
    <nav class="navbar navbar-light bg-light fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'Users:Home' %}">USER<b class="text-primary">PROFILE</b></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">MENU</h5>
          <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'Users:Home' %}"><i class="fas fa-home"></i> Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'Blog:UserPosts' %}"><i class="fas fa-blog"></i> Posts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'Blog:Add' %}"><i class="fas fa-plus-circle"></i> Add Post</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'Users:Settings' %}"><i class="fas fa-sliders-h"></i> Settings</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'Users:SignOut' %}"><i class="fas fa-sign-out-alt"></i> SignOut</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
{% block content %}


{% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
    -->
  </body>
</html>